import 'Environment.dart';

class APIConstant {
  static String insertUserFCM = "insertUserFCM.php";
  static String manageBrokers = "manage-brokers.php";
  static String manageProperties = "manage-properties.php";
  static String manageFilters = "manage-filters.php";
  static String manageStatus = "manage-status.php";
  static String manageFollowUp = "manage-followup.php";
  static String manageDeal = "manage-deal.php";
  static String manageLeadSources = "manage-lead-sources.php";
  static String manageLeads = "manage-leads.php";
  static String manageDashboard = "manage-dashboard.php";
  static String manageCategories = "manage-categories.php";
  static String manageCities = "manage-cities.php";
  static String manageAreas = "manage-areas.php";
  static String manageSubAreas = "manage-sub-areas.php";
  static String getPlanType = "getPlanType.php";
  static String getCompany = "getCompany.php";
  static String getPlanName = "getPlanName.php";
  static String managePolicies = "manage-policies.php";
  static String manageClaims = "manage-claims.php";
  static String getContactUs = "getContactUs.php";
  static String getTollFree = "getTollFree.php";
  static String getRelations = "getRelations.php";
  static String getNotifications = "getNotifications.php";

  // Special Requests Retrieved
  static String act = "act";
  static String type = "type";

  static String getByBroker = "FETCHBYBROKER";
  static String getByWishlist = "FETCHBYWISHLIST";
  static String getByID = "FETCHBYID";
  static String getByINID = "FETCHBYINID";
  static String getByPID = "FETCHBYPID";
  static String getByPAID = "FETCHBYPAID";
  static String getByAID = "FETCHBYAID";
  static String getByBID = "FETCHBYBID";
  static String getByStatus = "FETCHBYSTATUS";
  static String getByCID = "FETCHBYCID";
  static String getBySID = "FETCHBYSID";
  static String getByName = "FETCHBYNAME";
  static String getPopular = "FETCHPOPULAR";
  static String getByTime = "FETCHBYTIME";
  static String getByHotel = "FETCHBYHOTEL";
  static String getAll = "FETCHALL";
  static String getDashboard = "FETCHDASHBOARD";
  static String getRenewal = "FETCHRENEWAL";
  static String getDateRenewal = "FETCHDATERENEWAL";
  static String getMonthRenewal = "FETCHMONTHRENEWAL";
  static String getByPlanType = "FETCHBYPLANTYPE";
  static String getByCategory = "FETCHBYCATEGORY";
  static String getHealthClaims = "FETCHHEALTHCLAIMS";
  static String getMotorClaims = "FETCHMOTORCLAIMS";
  static String getRecommended = "FETCHRECOMMENDED";
  static String getNearby = "FETCHNEARBY";
  static String collection = "COLLECTION";
  static String recommended = "RECOMMENDED";
  static String holiday = "HOLIDAY";
  static String getBySlot = "FETCHBYSLOT";
  static String getByDate = "FETCHBYDATE";
  static String getR = "FETCHR";
  static String getTC = "FETCHTC";
  static String getGP = "FETCHGP";
  static String getPP = "FETCHPP";
  static String getCP = "FETCHCP";
  static String getAU = "FETCHAU";
  static String getHP = "FETCHHP";
  static String auth = "auth";
  static String addHealthClaim = "ADDHEALTHCLAIMS";
  static String addMotorClaim = "ADDMOTORCLAIMS";
  static String add = "add";
  static String login = "login";
  static String del = "DEL";
  static String update = "update";
  static String updateWishlist = "UPDATEWISHLIST";
  static String updateStatus = "UPDATESTATUS";
  static String delete = "DELETE";
  static String assign = "ASSIGN";
  static String verify = "verify";
  static String search = "SEARCH";
  static String getBySearch = "FETCHBYSEARCH";
  static String getByAcc = "FETCHBYACC";
  static String getByType = "FETCHBYTYPE";
  static String getByCity = "FETCHBYCITY";
  static String getByCitySearch = "FETCHBYCITYSEARCH";
  static String getByFilter = "FETCHBYFILTER";
  static String getByBanner = "FETCHBYBANNER";

  static String authorization = "Authorization";
  static String token = "Bearer ";

  static String symbol = "₹";
}
